name: Go test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Test
        run: make test

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: gwatts/go-coverage-action@v1
        id: coverage
        with:
          coverage-threshold: 90
          # collect coverage for all packages beyond the one under test
          cover-pkg: ./...
          # Ignore code-generated files when calculating coverage totals
          ignore-pattern: |
            \.pb\.go$
